apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: vote
spec:
  selector:
    matchLabels:
      app: result-deployment
  template:
    metadata:
      name: result-deployment
      labels:
        app: result-deployment
    spec:
      containers:
        - name: result-deployment
          image: kodekloud/examplevotingapp_result:before